version: 2

defaults: &defaults
  docker:
    - image: circleci/php:7.2.9-apache-node-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "package.json" }}
            - composer-{{ .Branch }}-{{ checksum "composer.json" }}
      - run:
          name: install php dev dependencies
          command: composer install --no-ansi --no-interaction --optimize-autoloader --no-progress
      - run:
          name: install node dev dependencies
          command: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - save_cache:
          key: composer-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - "vendor"
      - run:
          name: Validation
          command: |
            ./bin/circle-validation.sh
  deploy:
    <<: *defaults
    requires:
      - test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install node dev dependencies
          command: npm install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build and Push
          command: |
            ./bin/build-project.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
